[gcp_service_account]
type = "service_account"
project_id = "wedding-rsvp-456615"
private_key_id = "c49074bd76b5704dcf5da861088fe9ba84de379e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC3vy4RV6ni3o4+
cU2XLAZ2fOzhrcF2DsA4ZB9Vkp8b++l7CMCf833Vp0vXm9+AvVKUd36IpJQJ6ObW
g+nlbAv+NXs5JAobUQvKE83IRzmZ4LN6cbto9k+eR/IA92g8FApD+1xQrk5Qe1pS
psJo1ZUkc1oj60ltBZmg/6SI9odIcJ2cEhgf9N4BTO1ZzYxTdY7z5PR8tGKs7rGO
mWhNb/aF3H71Dx9hf5kNtcQCv3Q2GQe/4htPF8fgGyLS1ot7c4MPr+A2lVw2l3h2
ms41Tw/npW+iWOpSYi1x/bTVufunEO5/evEinQeykSMTe9parV9mDbZ/9tT8Fj7a
s2Q/7yVjAgMBAAECggEALn0DJcYdKFYQfQHjlJzB4daHhC2W5cyjm2DRgLAA626X
ytYTDiTnsFeMW7eHG6ZKr19wNxgUkFFJnfpwAeiNPDrBu1o/6Ftf9Td/d+11SFZO
cms19D9lM3GWa+IskA6t7jc5SvxeugQLfR/NzgJDop5ArxfHUvr4vIARW8mrvoq5
qLn/gdKDUPQia/XML/DTgyn+jWMVPz/uENJ7CUV5xsCthWVqlWGx0FLzVzkCuXOL
tS5biLOq3meZIF05VCKU2YQBmwhthdAiEmEysTmBvNtR/Grs49BjAauP+0g/GxK5
n8NatG1/gnWZPfECQ63RQhQSwnQYvoD51l+S439RKQKBgQDjGShakvPleGXE8hCj
eRB50mt/P4Ogd9f30Uho0jnH/UDjg0xM/Z93LrSpqAQHjxrRu/spj3jj1kqOgllL
2Zg57U8uOK4pZx2up4FRb3OMm2ujltAaJ2UCd+CC2gFuKsooRAbrjaFTaTyoCxae
BAIpiU+Aw9o0uwnNBMS9DQbQPQKBgQDPIaKLwvq/I7TZwXPhD23IiUfm6cMFdMIJ
KdTKX6zk7kDphSNtHG7ti/2SkAX7XdpEBeCaaDsU+uCwmZLiQ9Ecg1bP7ZlAhFJ/
NqmgzUPqFl9VIpopiPLXeuZ/vQCx3v+SnGWzyaDYNui/1nH8RSDf7azEE9sdHkyH
NrsM/UyGHwKBgEy1fb0CcGHthiq9PUOKrDcKDYeA87wrXwb1aUkG4b+c2uM+wXIs
JUZDv4CjISFQhFWd8pu6O7Jx+uMiQnlteY7vitRpDuMrUophSDwyskwnX3d1hLug
3Oy1g1+PtfX5fCmXuOKuB3U+Ud/NRwl+/x/6oqEzBqzTFN9soevdz5RdAoGAER7d
maHHKg9gfnNACcVFtMKsH8kIpqXM+AbuIMAhwVZ0JRktIXKtNJNSpU+kPu+1/9Ng
ikK9R3GpKs+21V73pNyyS0N/XFbTntI82R6+U1YAEUBn77DzKZ5t+Pb9XLZq94pX
2bF7ywNW36xxBYINQpUZp6dggBqmBrMeaOdy8M8CgYEAq1lM31dFY3d75BzsyNyw
ld1a5CsnQ6CT9bJG2f9tmhjXr7MRdkejwJg4ejLUbAmMod49iVVQYamAmmlXVg5e
3ysQab9XUH8O4CZ8m8BPn+R+WtGEk1ex8z+UsabdEhIetlJ2yXRoAUWpFaONYOrW
cxQhmFvUPd5y2gYIzkDdqP0=
-----END PRIVATE KEY-----"""
client_email = "streamlit-rsvp-sheets@wedding-rsvp-456615.iam.gserviceaccount.com"
client_id = "107585131064536157860"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-rsvp-sheets%40wedding-rsvp-456615.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
